# Generated by Django 2.0.2 on 2018-03-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('benefit', models.TextField()),
                ('normal', models.TextField()),
                ('special', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField()),
                ('full_text', models.TextField()),
                ('goal', models.TextField()),
                ('completion_benefit', models.TextField()),
                ('req_dex', models.IntegerField(default=None, null=True)),
                ('req_str', models.IntegerField(default=None, null=True)),
                ('req_con', models.IntegerField(default=None, null=True)),
                ('req_int', models.IntegerField(default=None, null=True)),
                ('req_wis', models.IntegerField(default=None, null=True)),
                ('req_cha', models.IntegerField(default=None, null=True)),
                ('req_bab', models.IntegerField(default=None, null=True)),
                ('caster_lvl', models.IntegerField(default=None, null=True)),
                ('caster_type', models.CharField(blank=True, choices=[('A', 'Arcane'), ('D', 'Divine')], max_length=1)),
                ('spell_lvl', models.IntegerField(default=None, null=True)),
                ('spell_type', models.CharField(blank=True, choices=[('A', 'Arcane'), ('D', 'Divine')], max_length=1)),
                ('teamwork', models.BooleanField(default=False)),
                ('critical', models.BooleanField(default=False)),
                ('grit', models.BooleanField(default=False)),
                ('style', models.BooleanField(default=False)),
                ('performance', models.BooleanField(default=False)),
                ('racial', models.BooleanField(default=False)),
                ('companion_familiar', models.BooleanField(default=False)),
                ('multiples', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='feat',
            name='feat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feats.FeatType'),
        ),
        migrations.AddField(
            model_name='feat',
            name='req_feats',
            field=models.ManyToManyField(blank=True, related_name='_feat_req_feats_+', to='feats.Feat'),
        ),
        migrations.AddField(
            model_name='feat',
            name='req_races',
            field=models.ManyToManyField(blank=True, to='feats.Race'),
        ),
        migrations.AddField(
            model_name='feat',
            name='suggested_traits',
            field=models.ManyToManyField(blank=True, to='feats.Trait'),
        ),
    ]
