# Generated by Django 2.0.2 on 2018-03-06 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ClassFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='feat',
            name='req_lvl',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='feat',
            name='req_traits',
            field=models.ManyToManyField(blank=True, related_name='_feat_req_traits_+', to='feats.Trait'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='req_feats',
            field=models.ManyToManyField(blank=True, to='feats.Feat'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='req_races',
            field=models.ManyToManyField(blank=True, related_name='_feat_req_races_+', to='feats.Race'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='suggested_traits',
            field=models.ManyToManyField(blank=True, related_name='_feat_suggested_traits_+', to='feats.Trait'),
        ),
        migrations.AddField(
            model_name='requiredskill',
            name='feat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feats.Feat'),
        ),
        migrations.AddField(
            model_name='requiredskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='feats.Skill'),
        ),
        migrations.AddField(
            model_name='class',
            name='features',
            field=models.ManyToManyField(to='feats.ClassFeature'),
        ),
        migrations.AddField(
            model_name='feat',
            name='req_class_features',
            field=models.ManyToManyField(blank=True, related_name='_feat_req_class_features_+',
                                         to='feats.ClassFeature'),
        ),
        migrations.AddField(
            model_name='feat',
            name='req_classes',
            field=models.ManyToManyField(blank=True, related_name='_feat_req_classes_+', to='feats.Class'),
        ),
        migrations.AddField(
            model_name='feat',
            name='req_skills',
            field=models.ManyToManyField(through='feats.RequiredSkill', to='feats.Skill'),
        ),
    ]
