# Generated by Django 2.0.3 on 2018-03-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feats', '0003_auto_20180306_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
