# Generated by Django 2.0.3 on 2018-03-14 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('feats', '0004_feat_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feat',
            old_name='full_text',
            new_name='html_text',
        ),
    ]
